# -*- coding: utf-8 -*-
"""Copy of Data Analysis project.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1omtL1vdQ5HKyldWbyV8lI7sJO6wuEjK1
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# -------------------------------
# STEP 1: CREATE HEALTH DATASET
# -------------------------------
data = {
    'Age': [25, 45, 35, 50, 23, 40, 60, 30],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'BMI': [22, 28, 30, 26, 24, 32, 29, 21],
    'Blood_Pressure': [120, 140, 135, 130, 118, 145, 150, 110],
    'Glucose': [90, 160, 140, 150, 95, 180, 170, 85],
    'Fracture': ['No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No'],
    'Disease': ['None', 'Diabetes', 'Heart', 'Diabetes', 'None', 'Heart', 'Diabetes', 'None']
}

df = pd.DataFrame(data)

print("\n--- HEALTH DATASET ---")
print(df)

# -------------------------------
# STEP 2: DATA VISUALIZATION
# -------------------------------

# Age vs Glucose
plt.scatter(df['Age'], df['Glucose'])
plt.xlabel('Age')
plt.ylabel('Glucose Level')
plt.title('Age vs Glucose Level')
plt.show()

# BMI Distribution
sns.histplot(df['BMI'], kde=True)
plt.title('BMI Distribution')
plt.show()

# Disease Distribution
df['Disease'].value_counts().plot(kind='bar')
plt.title('Disease Distribution')
plt.show()

# -------------------------------
# STEP 3: USER INPUT FOR HEALTH CHECK
# -------------------------------
print("\n--- ENTER PERSON DETAILS FOR HEALTH ANALYSIS ---")

age = int(input("Enter Age: "))
gender = input("Enter Gender: ")
bmi = float(input("Enter BMI: "))
bp = int(input("Enter Blood Pressure: "))
glucose = int(input("Enter Glucose Level: "))
fracture = input("Any Fracture (Yes/No): ")

# -------------------------------
# STEP 4: HEALTH ANALYSIS LOGIC
# -------------------------------
health_issues = []
recommendations = []

if glucose > 140:
    health_issues.append("Diabetes Risk")
    recommendations.append("Reduce sugar intake and do daily exercise")

if bmi > 30:
    health_issues.append("Obesity Risk")
    recommendations.append("Follow a balanced diet and increase physical activity")

if bp > 140:
    health_issues.append("High Blood Pressure")
    recommendations.append("Reduce salt intake and manage stress")

if fracture.lower() == "yes":
    health_issues.append("Bone Fracture Detected")
    recommendations.append("Increase calcium intake and take proper rest")

# -------------------------------
# STEP 5: FINAL REPORT
# -------------------------------
print("\n--- HEALTH ANALYSIS REPORT ---")

print(f"Age: {age}")
print(f"Gender: {gender}")
print(f"BMI: {bmi}")
print(f"Blood Pressure: {bp}")
print(f"Glucose Level: {glucose}")
print(f"Fracture: {fracture}")

if not health_issues:
    print("\nHealth Status: HEALTHY")
    print("Recommendation: Maintain a healthy lifestyle")
else:
    print("\nHealth Issues Detected:")
    for issue in health_issues:
        print("-", issue)

    print("\nHealth Recommendations:")
    for rec in recommendations:
        print("-", rec)